name: CI Pipeline Chat

on:
  push:
    branches: [ "main" ]
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login Dockerhub
      env: 
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      run: docker build -t cicd-pipeline-chat .
    
    - name: Tag Dockerhub
      run: docker tag cicd-pipeline-chat:latest ashishshukla6161/cicd-pipeline-chat:latest
    - name: Push to Dockerhub
      run: docker push ashishshukla6161/cicd-pipeline-chat:latest